title: RASHED ZAMAN
email: jmrashed@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio website of Rashed Zaman, Tech Lead.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jmrashed.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jmrashed
github_username:  jmrashed

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme settings
minima:
  skin: dark

# Analytics placeholder (replace with your actual analytics code)
analytics: UA-XXXXXXX-Y

# Sitemap settings
sitemap:
  exclude:
    - /assets/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/